#!/usr/bin/env python3
"""Sign and persist ssdf.audit chain-head checkpoints (MEC-565).

I/O shell around `ssdf_mcp_query.checkpoint_orchestrator.compute_next_checkpoint`
(pure decision logic, unit-tested on its own): reads each chain's currently
surviving rows and its previous checkpoint from ClickHouse as the
`ssdf_checkpoint` identity (022_audit_checkpoints.sql), asks the orchestrator
what the next checkpoint should say, shells out to the Rust
`mecmcp-audit-checkpoint` binary (mechubsec/mecmcp, crates/mecmcp-audit) to
sign it -- deterministic, no model in the loop -- and inserts the signed
result into `ssdf.audit_checkpoints`.

Key management (v1): a local Ed25519 private key file, generated by
`mecmcp-audit-keygen` and readable only by the account this script runs as
(the signing binary enforces 0600 and refuses otherwise -- the same
fail-closed check `mecmcp-audit`'s evidence signing already uses). Operators
who want HSM- or KMS-backed signing replace `--binary`/`CHECKPOINT_SIGNER_BIN`
with a wrapper that speaks the same stdin/stdout contract; this script has no
opinion on how the key is stored beyond "a path mecmcp-audit-checkpoint can
read".

Run periodically (e.g. daily) from the deploy's scheduler of choice -- this
script does not schedule itself, matching the signing binary's own stance
that it is not the orchestrator either.

Usage (from services/mcp-query, where the package is installed):
    export CH_HOST=... CH_CHECKPOINT_PASSWORD=...
    export CHECKPOINT_SIGNING_KEY_PATH=/etc/ssdf/checkpoint-signing.key
    uv run python scripts/checkpoint_audit.py [--binary mecmcp-audit-checkpoint]
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import subprocess
import sys
from collections import defaultdict

from ssdf_common.config import ConfigError, require_tls_or_loopback
from ssdf_mcp_query.checkpoint_orchestrator import compute_next_checkpoint
from ssdf_mcp_query.verify_audit import group_key

_ROW_COLUMNS = ["tier", "args", "prev_hash", "row_hash"]
_CHECKPOINT_COLUMNS = [
    "tier",
    "server_id",
    "row_count",
    "head_row_hash",
    "checkpoint_ts",
    "signature",
    "key_id",
]


def fetch_rows_by_chain(client) -> dict[tuple[str, str], list[dict]]:
    """Every chain's currently-stored, hashed rows, grouped by (tier, server_id).

    Excludes pre-chain legacy rows (row_hash == '', same convention as
    verify_audit.verify_tier) -- they were never part of any chain a
    checkpoint could anchor.
    """
    res = client.query(
        f"SELECT {', '.join(_ROW_COLUMNS)} FROM ssdf.audit WHERE row_hash != '' ORDER BY ts ASC"
    )
    by_chain: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for values in res.result_rows:
        row = dict(zip(_ROW_COLUMNS, values))
        by_chain[group_key(row)].append(row)
    return by_chain


def fetch_previous_checkpoints(client) -> dict[tuple[str, str], dict]:
    """Each chain's most recent prior checkpoint, as compute_next_checkpoint expects.

    Ordering by checkpoint_ts ascending and overwriting `latest` as we go
    means the last write per key wins -- the same "most recent" rule
    verify_audit._select_checkpoint_anchor uses (max by checkpoint_ts).
    """
    res = client.query(
        f"SELECT {', '.join(_CHECKPOINT_COLUMNS)} "
        "FROM ssdf.audit_checkpoints ORDER BY checkpoint_ts ASC"
    )
    latest: dict[tuple[str, str], dict] = {}
    for values in res.result_rows:
        row = dict(zip(_CHECKPOINT_COLUMNS, values))
        latest[(row["tier"], row["server_id"])] = row
    return latest


def format_checkpoint_ts(now: dt.datetime) -> str:
    """Millisecond-precision RFC3339 with a literal 'Z', matching the Rust
    signer's expected `checkpoint_ts` field (checkpoint.rs's usage string)."""
    if now.tzinfo is None:
        now = now.replace(tzinfo=dt.timezone.utc)
    now = now.astimezone(dt.timezone.utc)
    return now.strftime("%Y-%m-%dT%H:%M:%S.") + f"{now.microsecond // 1000:03d}Z"


def build_payload(pending, now: dt.datetime) -> dict:
    """The unsigned checkpoint JSON handed to mecmcp-audit-checkpoint on stdin."""
    return {
        "tier": pending.tier,
        "server_id": pending.server_id,
        "row_count": pending.row_count,
        "head_row_hash": pending.head_row_hash,
        "checkpoint_ts": format_checkpoint_ts(now),
    }


def sign_checkpoint(binary: str, key_path: str, payload: dict) -> dict:
    """Shell out to the Rust signer. Deterministic, no model in the loop.

    Fails closed: a non-zero exit, a timeout, or unparsable/incomplete stdout
    raises rather than letting an unsigned or partially-signed checkpoint
    reach the caller's insert path.
    """
    try:
        proc = subprocess.run(
            [binary, key_path],
            input=json.dumps(payload),
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise RuntimeError(f"could not run {binary!r}: {exc}") from exc
    if proc.returncode != 0:
        raise RuntimeError(f"{binary} failed: {proc.stderr.strip()}")
    try:
        signed = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"{binary} produced invalid JSON: {exc}") from exc
    missing = [c for c in _CHECKPOINT_COLUMNS if c not in signed]
    if missing:
        raise RuntimeError(f"{binary} output missing field(s): {missing}")
    return signed


def insert_checkpoint(client, signed: dict) -> None:
    client.insert(
        "ssdf.audit_checkpoints",
        [[signed[c] for c in _CHECKPOINT_COLUMNS]],
        column_names=_CHECKPOINT_COLUMNS,
    )


def run(client, binary: str, key_path: str, now: dt.datetime | None = None) -> list[dict]:
    """Checkpoint every chain that has rows newer than its last checkpoint.

    Returns the signed checkpoints that were inserted (empty list when every
    chain is already caught up), for logging and for tests.
    """
    now = now or dt.datetime.now(dt.timezone.utc)
    rows_by_chain = fetch_rows_by_chain(client)
    previous_by_chain = fetch_previous_checkpoints(client)
    inserted: list[dict] = []
    for chain, rows in sorted(rows_by_chain.items()):
        pending = compute_next_checkpoint(rows, previous_by_chain.get(chain))
        if pending is None:
            continue
        signed = sign_checkpoint(binary, key_path, build_payload(pending, now))
        insert_checkpoint(client, signed)
        inserted.append(signed)
    return inserted


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--binary",
        default=os.environ.get("CHECKPOINT_SIGNER_BIN", "mecmcp-audit-checkpoint"),
        help="path to the mecmcp-audit-checkpoint binary",
    )
    args = parser.parse_args()

    key_path = os.environ.get("CHECKPOINT_SIGNING_KEY_PATH")
    password = os.environ.get("CH_CHECKPOINT_PASSWORD")
    if not key_path:
        print("CHECKPOINT_SIGNING_KEY_PATH is required", file=sys.stderr)
        return 2
    if not password:
        print("CH_CHECKPOINT_PASSWORD is required", file=sys.stderr)
        return 2

    host = os.environ.get("CH_HOST", "127.0.0.1")
    secure = os.environ.get("CH_SECURE", "").strip().lower() in ("1", "true")
    try:
        require_tls_or_loopback(host, secure)
    except ConfigError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    import clickhouse_connect

    kwargs: dict = {}
    if secure:
        kwargs["interface"] = "https"
        ca_file = os.environ.get("CH_CA_FILE")
        if ca_file:
            kwargs["ca_cert"] = ca_file

    client = clickhouse_connect.get_client(
        host=host,
        port=int(os.environ.get("CH_PORT", "8123")),
        username="ssdf_checkpoint",
        password=password,
        database="ssdf",
        **kwargs,
    )

    try:
        inserted = run(client, args.binary, key_path)
    except RuntimeError as exc:
        print(f"checkpointing failed: {exc}", file=sys.stderr)
        return 1

    for cp in inserted:
        writer = f" server={cp['server_id']}" if cp["server_id"] else ""
        print(
            f"checkpointed tier={cp['tier']}{writer} "
            f"row_count={cp['row_count']} head={cp['head_row_hash'][:16]}…"
        )
    print(f"{len(inserted)} chain(s) checkpointed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
